language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get -y install qt510base qt510declarative binutils xpra
    - source /opt/qt510/bin/qt510-env.sh

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 5 # give xvfb some time to start

script:
  - cd src
  - sed -i '/include(packetsender_main.pri)/d' PacketSender.pro
  - cat packetsender_main.pri >> PacketSender.pro
  - tail PacketSender.pro
  - qmake --version
  - qmake PREFIX=/usr
  - make -j4
  - ls
  - mkdir -p appdir/usr/bin ; cd appdir
  - find ..
  - cp ../PacketSender usr/bin/
  - cp ../packetsender.desktop .
  - cp ../psicons.iconset/icon_256x256.png packetsender.png
  - cd ..
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/PacketSender -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/PacketSender -appimage
  - curl --upload-file ./PacketSender-*.AppImage https://transfer.sh/PacketSender-git$(git rev-parse --short HEAD)-x86_64.AppImage
