language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
    - sudo apt-get update -qq
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install: 
    - sudo apt-get install build-essential
    - sudo apt-get -y install qt58base qt58declarative binutils xpra

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 5 # give xvfb some time to start

script:
    - ls
    - cd src
    - ls    
    - qmake -qt=qt5 --version
    - ls    
    - qmake -qt=qt5
    - ls
    - make
    - ls
    - ./PacketSender --version
