language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    # C++11
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install: 
    - sudo apt-get install -qq qt5-default build-essential

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 5 # give xvfb some time to start

script:
    - ls
    - cd src
    - ls    
    - qmake -qt=qt5 --version
    - ls    
    - qmake -qt=qt5
    - ls
    - make
    - ls
    - ./PacketSender --version
