install:
    - set QTDIR=C:\Qt\5.8\mingw53_32
    - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\5.8\mingw53_32
build_script:
    - cd src
    - qmake PacketSender.pro
    - C:\Qt\Tools\mingw530_32\mingw32-make

