name: packetsender
version: 6.2.3.1
summary: Packet Sender Applicaiton
icon: src/packetsender.svg
description: |
  Packet Sender - Free utility to for sending / receiving of network
  packets. TCP, UDP, SSL.

# sudo snap install packetsender*.snap --dangerous

grade: devel
base: core18
confinement: strict

apps:
  packetsender:
    command: PacketSender
    plugs: [desktop, home]

parts:
  packetsender:
    plugin: qmake
    qt-version: qt5
    project-files: ["src/PacketSender.pro"]
    source: https://github.com/dannagle/PacketSender.git
    stage-packages: [libqt5gui5]
    build-packages:
      - qtbase5-dev
      - g++
      - gcc

