name: packetsender
version: 6.2.4
summary: Packet Sender Applicaiton
icon: src/packetsender.svg
description: |
  Packet Sender - Free utility to for sending / receiving of network
  packets. TCP, UDP, SSL.

# sudo snap install packetsender*.snap --dangerous

grade: devel
base: core18
confinement: strict
architectures: [amd64]

apps:
  packetsender:
    command: usr/local/bin/packetsender
    plugs: [desktop, home, network]
    environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu
parts:
  packetsender:
    plugin: qmake
    qt-version: qt5
    project-files: ["src/PacketSender.pro"]
    source: https://github.com/dannagle/PacketSender.git
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libqt5network5
      - libssl-dev
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all

    build-packages:
      - qtbase5-dev
      - g++
      - gcc

